on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git log ${{ github.event.pull_request.base.sha }}...${{ github.sha }} --pretty=format:"%H,%cd" --date=unix
