on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #with:
      #fetch-depth: 0
      #- run: echo '${{ toJSON(github) }}'
      #- run: echo ${{ github.sha }}
      #- run: echo ${{ github.base_ref }}
      #- run: echo ${{ github.event.pull_request.head.sha }}
      #- run: echo ${{ github.event.pull_request.base.sha }}
      - run: git log ${{ github.event.pull_request.base.sha }}...${{ github.sha }}
