on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo ${{ github.event.inputs.ref }}
      - run: |
          git log remotes/origin/main...${{ github.event.inputs.ref }}
