on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.base_ref }}
      - run: echo `git show-ref ${{ github.base_ref }} --verify`
      - run: |
          git log ${{ github.base_ref }}...${{ github.sha }}
